### ISSUE TITLE
XP tracking changes with callsign 

### ISSUE THREAD

**Issue by Drofseh** [Dzsek/pretense#20]
If a player changes their MP callsign Pretense treats them as a different player and tracks their XP under the new callsign, starting them at 0 XP again.

Example from my community's server:
I normally fly as Bat 9-9 but had changed to Chevy 1-1 for another mission and am now being tracked twice. Same with Fruitcake. 

Name
Chevy 1-1 | drofseh
Fruitcake
Hawg 1-2 | Fruitcake
Bat 9-9 | drofseh

XP
2965
2907
1176
194

**Comment by Dzsek** [comment]
Pretense profiles are based on the player name, since thats the only identifier you have available inside the mission environment.

If you so wish, you could technically implement some sort of server side logic to attempt merging profiles based on player UUIDs as these are available serverside, but you'd also need to keep a history of what UUIDs connected with what player names.

Not worth the effort in my opinion, and is beyond the scope of the mission. 

Way easier to just open up the stats file and merge it manually on the request of players.

**Comment by Drofseh** [comment]
Does the current setup not also mean that a someone could change their name to that of another player and spend that player's command tokens?

**Comment by Dzsek** [comment]
Yes it does.

**Comment by Drofseh** [comment]
That seems like a pretty easy exploit for griefers.

**Comment by Dzsek** [comment]
I'm not in the business of providing out of the box dedicated server solutions, nor have I ever claimed to be. Pretense I as meant to be enjoyed either solo or with a small group of friends. 

Theres plenty more ways to exploit things in this mission if all you care about is ruining the fun for others. 

If you run it on a public server and you have a griefing problem that's on you, as a server admin, to solve.

**Comment by Drofseh** [comment]
It looks like `get_player_info` already returns an Unique Client Identifier if you do want to support it in the future.

https://wiki.hoggitworld.com/view/DCS_func_get_player_info

**Comment by Dzsek** [comment]
Its a serverside functuon.

Not in the mission environment.

**Comment by Drofseh** [comment]
Ahh, too bad
